# Available rules reference
# https://dart-lang.github.io/linter/

# Base linter configuration 
# https://github.com/passsy/dart-lint
include: package:lint/analysis_options.yaml

# Enable/disable rules
linter:
  rules:
    unawaited_futures: true

# Change the default severity of enabled rules
# analyzer:
#   errors:
#     name_of_the_rule: ignore|info|warning|error

# To suppress a specific rule on a specific line of code, place an 
# ignore comment above it (e.g: // ignore: name_of_the_rule).
# Note that an inline comment would work too, but the dart formatter
# may move it below.